# Proxmox connection details
proxmox:
  host:
  port:
  user:

# Default values for VMs
vm_defaults: 
  node: # Node where VM will be created on
  ssh_key: # SSH key (cat id_rsa.pub file and paste here as a string)
  dns: # DNS server for VM, defaults to DNS settings on proxmox host
  gateway: # Default gateway

# Define VMs below
vms:
  - name: test
    vm_id: 200
    template_id: # ID of VM template to create VM with
    username: # cloud-init username
    disk_size: 8G
    cpu_cores: 1
    memory: 1024
    ip: # IP address of VM, include prefix e.g. 192.168.0.20/24
