---
- name: Authenticate to API
  uri:
    url: "https://{{ proxmox.host }}:{{ proxmox.port }}/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ proxmox.user }}"
      password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    validate_certs: no
  register: auth

- name: Resize disks of VMs
  uri:
    url: "https://{{ proxmox.host }}:{{ proxmox.port }}/api2/json/nodes/{{ proxmox.node }}/qemu/{{ item.vm_id }}/resize"
    method: PUT
    headers: 
      Cookie: "PVEAuthCookie={{ auth.json.data.ticket }}"
      CSRFPreventionToken: "{{ auth.json.data.CSRFPreventionToken }}"
    body_format: form-urlencoded
    body:
      disk: scsi0
      size: "{{ item.disk_size }}"
    validate_certs: no
  loop: "{{ vms }}"

