---
- name: Provision virtual machines
  community.general.proxmox_kvm:
    api_user: "{{ proxmox.user }}"
    api_host: "{{ proxmox.host }}"
    node: "{{ proxmox.node }}"
    clone: "yes"
    full: yes
    vmid: "{{ item.template_id }}"
    newid: "{{ item.vm_id }}"
    name: "{{ item.name }}"
  loop: "{{ vms }}"

- name: Configure cloud-init drive
  community.general.proxmox_kvm:
    api_user: "{{ proxmox.user }}"
    api_host: "{{ proxmox.host }}"
    node: "{{ proxmox.node }}"
    vmid: "{{ item.vm_id }}"
    update: yes
    cores: "{{ item.cpu_cores }}"
    cpuunits: 1024
    memory: "{{ item.memory }}"
    vga: serial0
    ciuser: "{{ item.username }}"
    sshkeys: "{{ ssh_key }}"
    net:
      net0: 'virtio,bridge=vmbr0'
    ipconfig:
      ipconfig0: 'ip={{ item.ip }},gw={{ dns }}'
  loop: "{{ vms }}"

